#!/bin/bash

if ! [ $# -eq 1 ]
then
    echo "Usage: `basename $0` [start|restart|stop|status]"
    exit 1
fi

case "$1" in
    start)
        echo "Starting Nginx..."
        sudo service nginx start
        sleep 1
        echo "Starting PHP5..."
        sudo service php5-fpm start
        sleep 1
        echo "Starting c9 MySQL..."
        mysql-ctl start
        sleep 1
    ;;
    stop)
        echo "Stoppting Nginx..."
        sudo service nginx stop
        sleep 1
        echo "Stopping PHP5..."
        sudo service php5-fpm stop
        sleep 1
        echo "Stopping c9 MySQL..."
        mysql-ctl stop
        sleep 1
    ;;
    restart)
        echo "Restarting Nginx..."
        sudo service nginx restart
        sleep 1
        echo "Restarting PHP5..."
        sudo service php5-fpm restart
        sleep 1
        echo "Restarting c9 MySQL..."
        mysql-ctl restart
        sleep 1
    ;;
    status)
        sudo service nginx status
        sudo service php5-fpm status
        mysql-ctl status
        exit 0
    ;;
    *)
        echo "Usage: `basename $0` [start|restart|stop|status|install]"
    ;;
esac