#!/bin/bash

if ! [ $# -eq 1 ]
then
    echo "Usage: `basename $0` [start|restart|stop|status]"
    exit 1
fi

case "$1" in
    start)
        echo "Starting Nginx..."
        sudo service nginx start
        sleep 1
        echo "Starting PHP5..."
        sudo service php5-fpm start
        sleep 1
        echo "Starting c9 MySQL..."
        mysql-ctl start
        sleep 1
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    cli)
        cli
    ;;
    status)
        if isrunning
        then
            echo "running" 1>&2
        else
            echo "stopped" 1>&2
        fi
        exit 0
    ;;
    *)
        echo "Usage: `basename $0` [start|restart|stop|status|cli|install]"
    ;;
esac